/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessoriaVistoAmericanoRouteImport } from './routes/assessoria-visto-americano'
import { Route as ComoTirarVistoAmericanoRouteImport } from './routes/como-tirar-visto-americano'
import { Route as DocumentosVistoAmericanoRouteImport } from './routes/documentos-visto-americano'
import { Route as Ds160RouteImport } from './routes/ds-160'
import { Route as EspecialistaVistoAmericanoRouteImport } from './routes/especialista-visto-americano'
import { Route as LinksRouteImport } from './routes/links'
import { Route as QuantoCustaVistoAmericanoRouteImport } from './routes/quanto-custa-visto-americano'
import { Route as RenovarVistoAmericanoRouteImport } from './routes/renovar-visto-americano'
import { Route as VistoAmericanoAnapolisRouteImport } from './routes/visto-americano-anapolis'
import { Route as VistoAmericanoCriancasRouteImport } from './routes/visto-americano-criancas'
import { Route as VistoAmericanoEstudanteRouteImport } from './routes/visto-americano-estudante'
import { Route as VistoAmericanoFamiliaRouteImport } from './routes/visto-americano-familia'
import { Route as VistoAmericanoNegadoRouteImport } from './routes/visto-americano-negado'
import { Route as VistoAmericanoTurismoNegociosRouteImport } from './routes/visto-americano-turismo-negocios'
import { Route as VistoNegado214bRouteImport } from './routes/visto-negado-214b'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessoriaVistoAmericanoRoute =
  AssessoriaVistoAmericanoRouteImport.update({
    id: '/assessoria-visto-americano',
    path: '/assessoria-visto-americano',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComoTirarVistoAmericanoRoute = ComoTirarVistoAmericanoRouteImport.update({
  id: '/como-tirar-visto-americano',
  path: '/como-tirar-visto-americano',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosVistoAmericanoRoute =
  DocumentosVistoAmericanoRouteImport.update({
    id: '/documentos-visto-americano',
    path: '/documentos-visto-americano',
    getParentRoute: () => rootRouteImport,
  } as any)
const Ds160Route = Ds160RouteImport.update({
  id: '/ds-160',
  path: '/ds-160',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialistaVistoAmericanoRoute =
  EspecialistaVistoAmericanoRouteImport.update({
    id: '/especialista-visto-americano',
    path: '/especialista-visto-americano',
    getParentRoute: () => rootRouteImport,
  } as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantoCustaVistoAmericanoRoute =
  QuantoCustaVistoAmericanoRouteImport.update({
    id: '/quanto-custa-visto-americano',
    path: '/quanto-custa-visto-americano',
    getParentRoute: () => rootRouteImport,
  } as any)
const RenovarVistoAmericanoRoute = RenovarVistoAmericanoRouteImport.update({
  id: '/renovar-visto-americano',
  path: '/renovar-visto-americano',
  getParentRoute: () => rootRouteImport,
} as any)
const VistoAmericanoAnapolisRoute = VistoAmericanoAnapolisRouteImport.update({
  id: '/visto-americano-anapolis',
  path: '/visto-americano-anapolis',
  getParentRoute: () => rootRouteImport,
} as any)
const VistoAmericanoCriancasRoute = VistoAmericanoCriancasRouteImport.update({
  id: '/visto-americano-criancas',
  path: '/visto-americano-criancas',
  getParentRoute: () => rootRouteImport,
} as any)
const VistoAmericanoEstudanteRoute = VistoAmericanoEstudanteRouteImport.update({
  id: '/visto-americano-estudante',
  path: '/visto-americano-estudante',
  getParentRoute: () => rootRouteImport,
} as any)
const VistoAmericanoFamiliaRoute = VistoAmericanoFamiliaRouteImport.update({
  id: '/visto-americano-familia',
  path: '/visto-americano-familia',
  getParentRoute: () => rootRouteImport,
} as any)
const VistoAmericanoNegadoRoute = VistoAmericanoNegadoRouteImport.update({
  id: '/visto-americano-negado',
  path: '/visto-americano-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const VistoAmericanoTurismoNegociosRoute =
  VistoAmericanoTurismoNegociosRouteImport.update({
    id: '/visto-americano-turismo-negocios',
    path: '/visto-americano-turismo-negocios',
    getParentRoute: () => rootRouteImport,
  } as any)
const VistoNegado214bRoute = VistoNegado214bRouteImport.update({
  id: '/visto-negado-214b',
  path: '/visto-negado-214b',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessoria-visto-americano': typeof AssessoriaVistoAmericanoRoute
  '/como-tirar-visto-americano': typeof ComoTirarVistoAmericanoRoute
  '/documentos-visto-americano': typeof DocumentosVistoAmericanoRoute
  '/ds-160': typeof Ds160Route
  '/especialista-visto-americano': typeof EspecialistaVistoAmericanoRoute
  '/links': typeof LinksRoute
  '/quanto-custa-visto-americano': typeof QuantoCustaVistoAmericanoRoute
  '/renovar-visto-americano': typeof RenovarVistoAmericanoRoute
  '/visto-americano-anapolis': typeof VistoAmericanoAnapolisRoute
  '/visto-americano-criancas': typeof VistoAmericanoCriancasRoute
  '/visto-americano-estudante': typeof VistoAmericanoEstudanteRoute
  '/visto-americano-familia': typeof VistoAmericanoFamiliaRoute
  '/visto-americano-negado': typeof VistoAmericanoNegadoRoute
  '/visto-americano-turismo-negocios': typeof VistoAmericanoTurismoNegociosRoute
  '/visto-negado-214b': typeof VistoNegado214bRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessoria-visto-americano': typeof AssessoriaVistoAmericanoRoute
  '/como-tirar-visto-americano': typeof ComoTirarVistoAmericanoRoute
  '/documentos-visto-americano': typeof DocumentosVistoAmericanoRoute
  '/ds-160': typeof Ds160Route
  '/especialista-visto-americano': typeof EspecialistaVistoAmericanoRoute
  '/links': typeof LinksRoute
  '/quanto-custa-visto-americano': typeof QuantoCustaVistoAmericanoRoute
  '/renovar-visto-americano': typeof RenovarVistoAmericanoRoute
  '/visto-americano-anapolis': typeof VistoAmericanoAnapolisRoute
  '/visto-americano-criancas': typeof VistoAmericanoCriancasRoute
  '/visto-americano-estudante': typeof VistoAmericanoEstudanteRoute
  '/visto-americano-familia': typeof VistoAmericanoFamiliaRoute
  '/visto-americano-negado': typeof VistoAmericanoNegadoRoute
  '/visto-americano-turismo-negocios': typeof VistoAmericanoTurismoNegociosRoute
  '/visto-negado-214b': typeof VistoNegado214bRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessoria-visto-americano': typeof AssessoriaVistoAmericanoRoute
  '/como-tirar-visto-americano': typeof ComoTirarVistoAmericanoRoute
  '/documentos-visto-americano': typeof DocumentosVistoAmericanoRoute
  '/ds-160': typeof Ds160Route
  '/especialista-visto-americano': typeof EspecialistaVistoAmericanoRoute
  '/links': typeof LinksRoute
  '/quanto-custa-visto-americano': typeof QuantoCustaVistoAmericanoRoute
  '/renovar-visto-americano': typeof RenovarVistoAmericanoRoute
  '/visto-americano-anapolis': typeof VistoAmericanoAnapolisRoute
  '/visto-americano-criancas': typeof VistoAmericanoCriancasRoute
  '/visto-americano-estudante': typeof VistoAmericanoEstudanteRoute
  '/visto-americano-familia': typeof VistoAmericanoFamiliaRoute
  '/visto-americano-negado': typeof VistoAmericanoNegadoRoute
  '/visto-americano-turismo-negocios': typeof VistoAmericanoTurismoNegociosRoute
  '/visto-negado-214b': typeof VistoNegado214bRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessoria-visto-americano'
    | '/como-tirar-visto-americano'
    | '/documentos-visto-americano'
    | '/ds-160'
    | '/especialista-visto-americano'
    | '/links'
    | '/quanto-custa-visto-americano'
    | '/renovar-visto-americano'
    | '/visto-americano-anapolis'
    | '/visto-americano-criancas'
    | '/visto-americano-estudante'
    | '/visto-americano-familia'
    | '/visto-americano-negado'
    | '/visto-americano-turismo-negocios'
    | '/visto-negado-214b'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessoria-visto-americano'
    | '/como-tirar-visto-americano'
    | '/documentos-visto-americano'
    | '/ds-160'
    | '/especialista-visto-americano'
    | '/links'
    | '/quanto-custa-visto-americano'
    | '/renovar-visto-americano'
    | '/visto-americano-anapolis'
    | '/visto-americano-criancas'
    | '/visto-americano-estudante'
    | '/visto-americano-familia'
    | '/visto-americano-negado'
    | '/visto-americano-turismo-negocios'
    | '/visto-negado-214b'
  id:
    | '__root__'
    | '/'
    | '/assessoria-visto-americano'
    | '/como-tirar-visto-americano'
    | '/documentos-visto-americano'
    | '/ds-160'
    | '/especialista-visto-americano'
    | '/links'
    | '/quanto-custa-visto-americano'
    | '/renovar-visto-americano'
    | '/visto-americano-anapolis'
    | '/visto-americano-criancas'
    | '/visto-americano-estudante'
    | '/visto-americano-familia'
    | '/visto-americano-negado'
    | '/visto-americano-turismo-negocios'
    | '/visto-negado-214b'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessoriaVistoAmericanoRoute: typeof AssessoriaVistoAmericanoRoute
  ComoTirarVistoAmericanoRoute: typeof ComoTirarVistoAmericanoRoute
  DocumentosVistoAmericanoRoute: typeof DocumentosVistoAmericanoRoute
  Ds160Route: typeof Ds160Route
  EspecialistaVistoAmericanoRoute: typeof EspecialistaVistoAmericanoRoute
  LinksRoute: typeof LinksRoute
  QuantoCustaVistoAmericanoRoute: typeof QuantoCustaVistoAmericanoRoute
  RenovarVistoAmericanoRoute: typeof RenovarVistoAmericanoRoute
  VistoAmericanoAnapolisRoute: typeof VistoAmericanoAnapolisRoute
  VistoAmericanoCriancasRoute: typeof VistoAmericanoCriancasRoute
  VistoAmericanoEstudanteRoute: typeof VistoAmericanoEstudanteRoute
  VistoAmericanoFamiliaRoute: typeof VistoAmericanoFamiliaRoute
  VistoAmericanoNegadoRoute: typeof VistoAmericanoNegadoRoute
  VistoAmericanoTurismoNegociosRoute: typeof VistoAmericanoTurismoNegociosRoute
  VistoNegado214bRoute: typeof VistoNegado214bRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessoria-visto-americano': {
      id: '/assessoria-visto-americano'
      path: '/assessoria-visto-americano'
      fullPath: '/assessoria-visto-americano'
      preLoaderRoute: typeof AssessoriaVistoAmericanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-tirar-visto-americano': {
      id: '/como-tirar-visto-americano'
      path: '/como-tirar-visto-americano'
      fullPath: '/como-tirar-visto-americano'
      preLoaderRoute: typeof ComoTirarVistoAmericanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos-visto-americano': {
      id: '/documentos-visto-americano'
      path: '/documentos-visto-americano'
      fullPath: '/documentos-visto-americano'
      preLoaderRoute: typeof DocumentosVistoAmericanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds-160': {
      id: '/ds-160'
      path: '/ds-160'
      fullPath: '/ds-160'
      preLoaderRoute: typeof Ds160RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialista-visto-americano': {
      id: '/especialista-visto-americano'
      path: '/especialista-visto-americano'
      fullPath: '/especialista-visto-americano'
      preLoaderRoute: typeof EspecialistaVistoAmericanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quanto-custa-visto-americano': {
      id: '/quanto-custa-visto-americano'
      path: '/quanto-custa-visto-americano'
      fullPath: '/quanto-custa-visto-americano'
      preLoaderRoute: typeof QuantoCustaVistoAmericanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovar-visto-americano': {
      id: '/renovar-visto-americano'
      path: '/renovar-visto-americano'
      fullPath: '/renovar-visto-americano'
      preLoaderRoute: typeof RenovarVistoAmericanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visto-americano-anapolis': {
      id: '/visto-americano-anapolis'
      path: '/visto-americano-anapolis'
      fullPath: '/visto-americano-anapolis'
      preLoaderRoute: typeof VistoAmericanoAnapolisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visto-americano-criancas': {
      id: '/visto-americano-criancas'
      path: '/visto-americano-criancas'
      fullPath: '/visto-americano-criancas'
      preLoaderRoute: typeof VistoAmericanoCriancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visto-americano-estudante': {
      id: '/visto-americano-estudante'
      path: '/visto-americano-estudante'
      fullPath: '/visto-americano-estudante'
      preLoaderRoute: typeof VistoAmericanoEstudanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visto-americano-familia': {
      id: '/visto-americano-familia'
      path: '/visto-americano-familia'
      fullPath: '/visto-americano-familia'
      preLoaderRoute: typeof VistoAmericanoFamiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visto-americano-negado': {
      id: '/visto-americano-negado'
      path: '/visto-americano-negado'
      fullPath: '/visto-americano-negado'
      preLoaderRoute: typeof VistoAmericanoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visto-americano-turismo-negocios': {
      id: '/visto-americano-turismo-negocios'
      path: '/visto-americano-turismo-negocios'
      fullPath: '/visto-americano-turismo-negocios'
      preLoaderRoute: typeof VistoAmericanoTurismoNegociosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visto-negado-214b': {
      id: '/visto-negado-214b'
      path: '/visto-negado-214b'
      fullPath: '/visto-negado-214b'
      preLoaderRoute: typeof VistoNegado214bRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessoriaVistoAmericanoRoute: AssessoriaVistoAmericanoRoute,
  ComoTirarVistoAmericanoRoute: ComoTirarVistoAmericanoRoute,
  DocumentosVistoAmericanoRoute: DocumentosVistoAmericanoRoute,
  Ds160Route: Ds160Route,
  EspecialistaVistoAmericanoRoute: EspecialistaVistoAmericanoRoute,
  LinksRoute: LinksRoute,
  QuantoCustaVistoAmericanoRoute: QuantoCustaVistoAmericanoRoute,
  RenovarVistoAmericanoRoute: RenovarVistoAmericanoRoute,
  VistoAmericanoAnapolisRoute: VistoAmericanoAnapolisRoute,
  VistoAmericanoCriancasRoute: VistoAmericanoCriancasRoute,
  VistoAmericanoEstudanteRoute: VistoAmericanoEstudanteRoute,
  VistoAmericanoFamiliaRoute: VistoAmericanoFamiliaRoute,
  VistoAmericanoNegadoRoute: VistoAmericanoNegadoRoute,
  VistoAmericanoTurismoNegociosRoute: VistoAmericanoTurismoNegociosRoute,
  VistoNegado214bRoute: VistoNegado214bRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
