/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessoriaVistoAmericanoRouteImport } from './routes/assessoria-visto-americano'
import { Route as ComoTirarVistoAmericanoRouteImport } from './routes/como-tirar-visto-americano'
import { Route as DocumentosVistoAmericanoRouteImport } from './routes/documentos-visto-americano'
import { Route as EspecialistaVistoAmericanoRouteImport } from './routes/especialista-visto-americano'
import { Route as RenovarVistoAmericanoRouteImport } from './routes/renovar-visto-americano'
import { Route as VistoAmericanoCriancasRouteImport } from './routes/visto-americano-criancas'
import { Route as VistoAmericanoFamiliaRouteImport } from './routes/visto-americano-familia'
import { Route as VistoAmericanoGoianiaRouteImport } from './routes/visto-americano-goiania'
import { Route as VistoAmericanoNegadoRouteImport } from './routes/visto-americano-negado'
import { Route as VistoNegado214bRouteImport } from './routes/visto-negado-214b'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessoriaVistoAmericanoRoute =
  AssessoriaVistoAmericanoRouteImport.update({
    id: '/assessoria-visto-americano',
    path: '/assessoria-visto-americano',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComoTirarVistoAmericanoRoute = ComoTirarVistoAmericanoRouteImport.update({
  id: '/como-tirar-visto-americano',
  path: '/como-tirar-visto-americano',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosVistoAmericanoRoute =
  DocumentosVistoAmericanoRouteImport.update({
    id: '/documentos-visto-americano',
    path: '/documentos-visto-americano',
    getParentRoute: () => rootRouteImport,
  } as any)
const EspecialistaVistoAmericanoRoute =
  EspecialistaVistoAmericanoRouteImport.update({
    id: '/especialista-visto-americano',
    path: '/especialista-visto-americano',
    getParentRoute: () => rootRouteImport,
  } as any)
const RenovarVistoAmericanoRoute = RenovarVistoAmericanoRouteImport.update({
  id: '/renovar-visto-americano',
  path: '/renovar-visto-americano',
  getParentRoute: () => rootRouteImport,
} as any)
const VistoAmericanoCriancasRoute = VistoAmericanoCriancasRouteImport.update({
  id: '/visto-americano-criancas',
  path: '/visto-americano-criancas',
  getParentRoute: () => rootRouteImport,
} as any)
const VistoAmericanoFamiliaRoute = VistoAmericanoFamiliaRouteImport.update({
  id: '/visto-americano-familia',
  path: '/visto-americano-familia',
  getParentRoute: () => rootRouteImport,
} as any)
const VistoAmericanoGoianiaRoute = VistoAmericanoGoianiaRouteImport.update({
  id: '/visto-americano-goiania',
  path: '/visto-americano-goiania',
  getParentRoute: () => rootRouteImport,
} as any)
const VistoAmericanoNegadoRoute = VistoAmericanoNegadoRouteImport.update({
  id: '/visto-americano-negado',
  path: '/visto-americano-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const VistoNegado214bRoute = VistoNegado214bRouteImport.update({
  id: '/visto-negado-214b',
  path: '/visto-negado-214b',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessoria-visto-americano': typeof AssessoriaVistoAmericanoRoute
  '/como-tirar-visto-americano': typeof ComoTirarVistoAmericanoRoute
  '/documentos-visto-americano': typeof DocumentosVistoAmericanoRoute
  '/especialista-visto-americano': typeof EspecialistaVistoAmericanoRoute
  '/renovar-visto-americano': typeof RenovarVistoAmericanoRoute
  '/visto-americano-criancas': typeof VistoAmericanoCriancasRoute
  '/visto-americano-familia': typeof VistoAmericanoFamiliaRoute
  '/visto-americano-goiania': typeof VistoAmericanoGoianiaRoute
  '/visto-americano-negado': typeof VistoAmericanoNegadoRoute
  '/visto-negado-214b': typeof VistoNegado214bRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessoria-visto-americano': typeof AssessoriaVistoAmericanoRoute
  '/como-tirar-visto-americano': typeof ComoTirarVistoAmericanoRoute
  '/documentos-visto-americano': typeof DocumentosVistoAmericanoRoute
  '/especialista-visto-americano': typeof EspecialistaVistoAmericanoRoute
  '/renovar-visto-americano': typeof RenovarVistoAmericanoRoute
  '/visto-americano-criancas': typeof VistoAmericanoCriancasRoute
  '/visto-americano-familia': typeof VistoAmericanoFamiliaRoute
  '/visto-americano-goiania': typeof VistoAmericanoGoianiaRoute
  '/visto-americano-negado': typeof VistoAmericanoNegadoRoute
  '/visto-negado-214b': typeof VistoNegado214bRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessoria-visto-americano': typeof AssessoriaVistoAmericanoRoute
  '/como-tirar-visto-americano': typeof ComoTirarVistoAmericanoRoute
  '/documentos-visto-americano': typeof DocumentosVistoAmericanoRoute
  '/especialista-visto-americano': typeof EspecialistaVistoAmericanoRoute
  '/renovar-visto-americano': typeof RenovarVistoAmericanoRoute
  '/visto-americano-criancas': typeof VistoAmericanoCriancasRoute
  '/visto-americano-familia': typeof VistoAmericanoFamiliaRoute
  '/visto-americano-goiania': typeof VistoAmericanoGoianiaRoute
  '/visto-americano-negado': typeof VistoAmericanoNegadoRoute
  '/visto-negado-214b': typeof VistoNegado214bRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessoria-visto-americano'
    | '/como-tirar-visto-americano'
    | '/documentos-visto-americano'
    | '/especialista-visto-americano'
    | '/renovar-visto-americano'
    | '/visto-americano-criancas'
    | '/visto-americano-familia'
    | '/visto-americano-goiania'
    | '/visto-americano-negado'
    | '/visto-negado-214b'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessoria-visto-americano'
    | '/como-tirar-visto-americano'
    | '/documentos-visto-americano'
    | '/especialista-visto-americano'
    | '/renovar-visto-americano'
    | '/visto-americano-criancas'
    | '/visto-americano-familia'
    | '/visto-americano-goiania'
    | '/visto-americano-negado'
    | '/visto-negado-214b'
  id:
    | '__root__'
    | '/'
    | '/assessoria-visto-americano'
    | '/como-tirar-visto-americano'
    | '/documentos-visto-americano'
    | '/especialista-visto-americano'
    | '/renovar-visto-americano'
    | '/visto-americano-criancas'
    | '/visto-americano-familia'
    | '/visto-americano-goiania'
    | '/visto-americano-negado'
    | '/visto-negado-214b'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessoriaVistoAmericanoRoute: typeof AssessoriaVistoAmericanoRoute
  ComoTirarVistoAmericanoRoute: typeof ComoTirarVistoAmericanoRoute
  DocumentosVistoAmericanoRoute: typeof DocumentosVistoAmericanoRoute
  EspecialistaVistoAmericanoRoute: typeof EspecialistaVistoAmericanoRoute
  RenovarVistoAmericanoRoute: typeof RenovarVistoAmericanoRoute
  VistoAmericanoCriancasRoute: typeof VistoAmericanoCriancasRoute
  VistoAmericanoFamiliaRoute: typeof VistoAmericanoFamiliaRoute
  VistoAmericanoGoianiaRoute: typeof VistoAmericanoGoianiaRoute
  VistoAmericanoNegadoRoute: typeof VistoAmericanoNegadoRoute
  VistoNegado214bRoute: typeof VistoNegado214bRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessoria-visto-americano': {
      id: '/assessoria-visto-americano'
      path: '/assessoria-visto-americano'
      fullPath: '/assessoria-visto-americano'
      preLoaderRoute: typeof AssessoriaVistoAmericanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-tirar-visto-americano': {
      id: '/como-tirar-visto-americano'
      path: '/como-tirar-visto-americano'
      fullPath: '/como-tirar-visto-americano'
      preLoaderRoute: typeof ComoTirarVistoAmericanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos-visto-americano': {
      id: '/documentos-visto-americano'
      path: '/documentos-visto-americano'
      fullPath: '/documentos-visto-americano'
      preLoaderRoute: typeof DocumentosVistoAmericanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialista-visto-americano': {
      id: '/especialista-visto-americano'
      path: '/especialista-visto-americano'
      fullPath: '/especialista-visto-americano'
      preLoaderRoute: typeof EspecialistaVistoAmericanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovar-visto-americano': {
      id: '/renovar-visto-americano'
      path: '/renovar-visto-americano'
      fullPath: '/renovar-visto-americano'
      preLoaderRoute: typeof RenovarVistoAmericanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visto-americano-criancas': {
      id: '/visto-americano-criancas'
      path: '/visto-americano-criancas'
      fullPath: '/visto-americano-criancas'
      preLoaderRoute: typeof VistoAmericanoCriancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visto-americano-familia': {
      id: '/visto-americano-familia'
      path: '/visto-americano-familia'
      fullPath: '/visto-americano-familia'
      preLoaderRoute: typeof VistoAmericanoFamiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visto-americano-goiania': {
      id: '/visto-americano-goiania'
      path: '/visto-americano-goiania'
      fullPath: '/visto-americano-goiania'
      preLoaderRoute: typeof VistoAmericanoGoianiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visto-americano-negado': {
      id: '/visto-americano-negado'
      path: '/visto-americano-negado'
      fullPath: '/visto-americano-negado'
      preLoaderRoute: typeof VistoAmericanoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visto-negado-214b': {
      id: '/visto-negado-214b'
      path: '/visto-negado-214b'
      fullPath: '/visto-negado-214b'
      preLoaderRoute: typeof VistoNegado214bRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessoriaVistoAmericanoRoute: AssessoriaVistoAmericanoRoute,
  ComoTirarVistoAmericanoRoute: ComoTirarVistoAmericanoRoute,
  DocumentosVistoAmericanoRoute: DocumentosVistoAmericanoRoute,
  EspecialistaVistoAmericanoRoute: EspecialistaVistoAmericanoRoute,
  RenovarVistoAmericanoRoute: RenovarVistoAmericanoRoute,
  VistoAmericanoCriancasRoute: VistoAmericanoCriancasRoute,
  VistoAmericanoFamiliaRoute: VistoAmericanoFamiliaRoute,
  VistoAmericanoGoianiaRoute: VistoAmericanoGoianiaRoute,
  VistoAmericanoNegadoRoute: VistoAmericanoNegadoRoute,
  VistoNegado214bRoute: VistoNegado214bRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
